---
title: "check_for_coding_household_level"
author: "Pascal_Ntaganda"
date: "2/18/2022"
output: html_document
---

Contents(Variables): This section has different variables for the different 6 rounds [KEY: described as indices]


SEC4 (Coding is similar in all respective rounds' variables)
---------------
Round1: 1:7,7a:c,8:20
Round2: 1e:f, 1:4,8:12
Round3: 5:14
Round4: 1e:g,1:4,8:11,11a:b,12:18
Round5: 5:15,15_1,16:18
Round6: 1e:g,1:4,4_1,4_2,4_3,4_4,4_5,8,12:14,19:22
Round7: 12:22 (different variable description as compared to counter parts)

Coding (Example of how I was checking the coding and questions in every variable.)
----------------

Variable 1:

Round1: 
In the last week did you have sufficient soap to wash your hands when needed?
YES ..........1>>3
NO ...........2 

Round 2:
In last 7 days week did you have sufficient soap to wash your hands when needed?
YES ..........1 >>3
NO ...........2 


Round 6:
In the last 7 days did you have sufficient soap to wash your hands when needed?
YES ..........1>>3
NO ...........2 

---------------------------------------------------------------------------------------------------
Variable 2:

Round1:
"What was the main reason you or members of your household were unable to access sufficient soap to wash hands?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"
SHOPS HAVE RUN OUT OF STOCK ...1
LOCAL MARKETS NOT OPERATING / CLOSED ........................2 
LIMITED / NO TRANSPORTATION....3
RESTRICTION TO GO OUTSIDE .....4
INCREASE IN PRICE .............5
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........6
CANNOT AFFORD IT ..............7
AFRAID TO GET OUT AND GETTING THE VIRUS......................8
OTHER .......................-96
REFUSED TO RESPOND ...........99

Round2:
"What was the main reason you or members of your household were unable to access sufficient soap to wash hands?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"

SHOPS HAVE RUN OUT OF STOCK ...1
LOCAL MARKETS NOT OPERATING / CLOSED ........................2 
LIMITED / NO TRANSPORTATION....3
RESTRICTION TO GO OUTSIDE .....4
INCREASE IN PRICE .............5
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........6
CANNOT AFFORD IT ..............7
AFRAID TO GET OUT AND GETTING THE VIRUS......................8
OTHER .........................9
REFUSED TO RESPOND ...........99



Round4:
"What was the main reason you or members of your household were unable to access sufficient soap to wash hands?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"
SHOPS HAVE RUN OUT OF STOCK ...1
LOCAL MARKETS NOT OPERATING / CLOSED ........................2 
LIMITED / NO TRANSPORTATION....3
RESTRICTION TO GO OUTSIDE .....4
INCREASE IN PRICE .............5
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........6
CANNOT AFFORD IT ..............7
AFRAID TO GET OUT AND GETTING THE VIRUS......................8
OTHER .........................9
REFUSED TO RESPOND ...........99

Round6:

"What was the main reason you or members of your household were unable to access sufficient soap to wash hands?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"
SHOPS HAVE RUN OUT OF STOCK ...1
LOCAL MARKETS NOT OPERATING / CLOSED ........................2 
LIMITED / NO TRANSPORTATION....3
RESTRICTION TO GO OUTSIDE .....4
INCREASE IN PRICE .............5
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........6
CANNOT AFFORD IT ..............7
AFRAID TO GET OUT AND GETTING THE VIRUS......................8
OTHER .........................9
REFUSED TO RESPOND ...........99


---------------------------------------------------------------------------------------------------

Variable 3:
Round 1:
In the last week, that is from Monday  up to Sunday, did you have sufficient water to wash your hands when needed?
YES ..........1>>5
NO ...........2 

Round 2:
In the last 7 days, that is from Monday  up to Sunday, did you have sufficient water to wash your hands when needed?

YES ..........1>>5
NO ...........2 


Round 4:

In the last week, that is from Monday  up to Sunday, did you have sufficient water to wash your hands when needed?

YES ..........1>>8
NO ...........2 


Round 6:

In the last 7 days, that is from Monday  up to Sunday, did you have sufficient water to wash your hands when needed?

YES ..........1>>4_1
NO ...........2 

---------------------------------------------------------------------------------------------------

Variable 4:
Round 1:
"What was the main reason your household was unable to access water to wash your hands ?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON

"
WATER SUPPLY NO LONGER 
AVAILABLE......................1
WATER SUPPLY REDUCED...........2
UNABLE TO ACCESS COMMUNAL 
SOURCES........................3
SHOPS HAVE RUN OUT OF STOCK ...4
LOCAL MARKETS NOT OPERATING / 
CLOSED ........................5 
LIMITED / NO TRANSPORTATION....6
RESTRICTION TO GO OUTSIDE .....7
INCREASE IN PRICE .............8
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........9
CANNOT AFFORD IT ..............10
AFRAID TO GET OUT AND GETTING THE VIRUS..........................11
OTHER ........................-96
REFUSED TO RESPOND.............99
---------------------------------------------------------------------------------------------------

Round 2:

"What was the main reason your household was unable to access water to wash your hands ?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"

WATER SUPPLY NO LONGER 
AVAILABLE......................1
WATER SUPPLY REDUCED...........2
UNABLE TO ACCESS COMMUNAL 
SOURCES........................3
SHOPS HAVE RUN OUT OF STOCK ...4
LOCAL MARKETS NOT OPERATING / 
CLOSED ........................5 
LIMITED / NO TRANSPORTATION....6
RESTRICTION TO GO OUTSIDE .....7
INCREASE IN PRICE .............8
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........9
CANNOT AFFORD IT ..............10
AFRAID TO GET OUT AND GETTING THE VIRUS..........................11
OTHER .........................12
REFUSED TO RESPOND.............99



Round 4:
"What was the main reason your household was unable to access water to wash your hands?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"

WATER SUPPLY NO LONGER 
AVAILABLE......................1
WATER SUPPLY REDUCED...........2
UNABLE TO ACCESS COMMUNAL 
SOURCES........................3
SHOPS HAVE RUN OUT OF STOCK ...4
LOCAL MARKETS NOT OPERATING / 
CLOSED ........................5 
LIMITED / NO TRANSPORTATION....6
RESTRICTION TO GO OUTSIDE .....7
INCREASE IN PRICE .............8
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........9
CANNOT AFFORD IT ..............10
AFRAID TO GET OUT AND GETTING THE VIRUS..........................11
OTHER .........................12
REFUSED TO RESPOND.............99



Round 6:

"What was the main reason your household was unable to access water to wash your hands ?
DO NOT READ OPTIONS
PLEASE PROBE AND SELECT THE MAIN REASON
"

WATER SUPPLY NO LONGER 
AVAILABLE......................1
WATER SUPPLY REDUCED...........2
UNABLE TO ACCESS COMMUNAL 
SOURCES........................3
SHOPS HAVE RUN OUT OF STOCK ...4
LOCAL MARKETS NOT OPERATING / 
CLOSED ........................5 
LIMITED / NO TRANSPORTATION....6
RESTRICTION TO GO OUTSIDE .....7
INCREASE IN PRICE .............8
NO ACCESS TO CASH AND CANNOT
PAY WITH CREDIT CARD ..........9
CANNOT AFFORD IT ..............10
AFRAID TO GET OUT AND GETTING THE VIRUS..........................11
OTHER .........................12
REFUSED TO RESPOND.............99

--------------------------------------------------------------------------------------------------------


Variable 5:

Round1: Main staple food 

MAIZE ..........1
RICE ...........2
MATOOKE.........3 
CASSAVA.........4
MILLET..........5
SORGHUM.........6
SWEET POTATOES..7
IRISH POTATOES..8


Round3: Main staple food

MAIZE ..........1
RICE ...........2
MATOOKE.........3 
CASSAVA.........4
MILLET..........5
SORGHUM.........6
SWEET POTATOES..7
IRISH POTATOES..8


Round5: Main staple food

Empty
---------------------------------------------------------------------------------------------------

Variable 6:
Round1:
In the last week, that is from Monday  up to Sunday, has your household been unable to buy [MAIN Staple Food ]?

YES ..........1
NO ...........2 >>7a 
NOT TRIED ....3 >>7a

Round3:

In the last 7 days, has your household been unable to buy [MAIN Staple Food ]?

YES ..........1
NO ...........2 >>8 
NOT TRIED ....3 >>8

Round5:

In the last 7 days, has your household been unable to buy [MAIN Staple Food]?

YES ..........1
NO ...........2 >>8 
NOT TRIED ....3 >>8

--------------------------------------------------------------------------------------------------------

Variable 12:

Round 1: Different variable description
Round 2: Different variable description

Round 2: Different variable description
Does your household own any of these assets?

The rest:
In the last 7 days, were you or any member of  your household unable to access masks?

--------------------------------------------------------------------------------------------------------

Variable 13:

Round 1: different variable description.
Were any of the children attending school before schools were closed due to corona virus?

--------------------------------------------------------------------------------------------------------

Variable 14:

Round 1: different variable description.
Have the children been engaged in any education or learning activities since the schools closed?

--------------------------------------------------------------------------------------------------------

Variable 15:

Round 1: different variable description.
In what types of education or learning activities have the children been engaged in the last week? 

Round 4 & 5:
If you could get tested for free for the COVID-19 virus, would you be willing to get tested?

Round 7:
In the last 7 days, has your household been able to buy medicine?

--------------------------------------------------------------------------------------------------------

Variable 16:

Round 1:
Have the children or anyone else in the household been in contact with their teachers in the last week?

Round 4 & 5:
If an approved vaccine to prevent coronavirus was available right now at no cost, would you agree to be vaccinated?

--------------------------------------------------------------------------------------------------------

Variable 17:

Round 1:
How have the children or others in your household been in contact with their teachers in the last week? 

Round 4 & 5:
What are the reasons you would not agree to be vaccinated?

--------------------------------------------------------------------------------------------------------

Variable 18:

Round 1:
In the last week, that is from Monday  up to Sunday , did you or any member of your household need to go to the bank, money agent (western union, moneygram, mobile money) or use the ATM?

Round 4 & 5:
What are the reasons you are not sure whether you would agree to be vaccinated?

--------------------------------------------------------------------------------------------------------

Variable 19:

Round 1:
Were you able to successfully access it?

Round 6 & 7:
Have you or any member of your household  needed any medical services ( treatment or consultation)  in the past 4 weeks whether there was illness or not?

--------------------------------------------------------------------------------------------------------

Variable 20:

Round 1:
Why were you not able to access it?

Round 6 & 7:
What type of service did you or any member of your household need?  

---------------------------------------------------------------------------------------------------
END OF DEMONSTRATION
---------------------------------------------------------------------------------------------------


SEC5 
---------------
Round1: 1a,1:4,4a:c,5:8,8a:c,9:14
Round2: 1,1a:c,3,3a:b,4a:b,5:8,8a:e,9:10
Round3: 1,1a:c,3,3a:b,4a:b,5:8,8a:c,8f:g,8g_1,9:10
Round4: 1,1a:c,3,3a:b,4a:b,5a,5:6,6a,7:8,8a:c,8f:g,8g_1,9:10
Round5: 1,1a:c,3,3a:b,4a:b,5a,5:6,6a
Round6(5resp): 1,1a:c,3,3a:b,4a:b,5a,5:6,6a,8b1:c1
Round6(5other): 0a:c,1,1a:d,3a:b,6,6a,5a,5,8b1,8c1
Round7: 1,1a:c,3,3a:b,4a:b,5a,5:6,6a,8f:g,8g_1,8b1:c1

Round 1: 
Variable 1a: (Different from the rest)

What is your highest level of Education? 
SOME PRIMARY........1
COMPLETED PRIMARY...2
SOMEE SECONDARY.....3
COMPLETED SECONDARY...........4
UNIVERSITY DEGREE...5
MASTER DEGREE.......6
PhD.................7
NO SCHOOL...........8
DIPLOMA.............9
CERTIFICATE........10
DON'T KNOW........-96
REFUSED TO RESPOND............99

Variable 4a: (Different coding)
YES.1 >>Q5
NO..2 

---------------------------------------------------------------------------------------------------

Variable 6:

Round 1, 2 and 3 have similar coding

In your own business ..................1 >>Q9
In a business operated by a 
household or family member ............2 >>Q9
In a family farm, raising family 
livestock or fishing ..................3 >>Q9
As an employee for someone else .......4 
As an apprentice, trainee, intern .....5 


Round 4:

In your own non-farm business..........1 >> Q9
In a non-farm business operated 
 by a household member.................2 >> Q9
In a family farm growing crops, raising
 livestock, or fishing.................3 
As an employee for a private company 
 or another individual (not household
 member)...............................4 >> Q7
As an employee for the government......5 >> Q7
As an apprentice, trainee, intern .....6 >> Q7

Round 5:

In your own non-farm business..........1 >> Q9
In a non-farm business operated 
 by a household member.................2 >> Q9
In a family farm growing crops, raising
 livestock, or fishing.................3 
As an employee for a private company 
 or another individual (not household
 member)...............................4 >> Q7
As an employee for the government......5 >> Q7
As an apprentice, trainee, intern .....6 >> Q7

Round 6(resp):

In your own business ..................1 >> Q8b1
In a business operated by a 
household or family member ............2 >> Q8b1
In a family farm growing crops, raising
 livestock, or fishing.................3 
As an employee for someone else .......4 >> Q8b1
As an apprentice, trainee, intern .....5 >> Q8b1

Round 6(other):

In your own non-farm business...1 >> Q5a
In a non-farm business operated 
 by a household member..........2 >> Q5a
In a familyfarm, growing crops, 
 raising livestock, or fishing..3 
As an employee for a private 
 company or another individual 
 (not household member) ........4 >> Q5a
As an employee for 
 the government.................5 >> Q5a
As an apprentice, trainee,
 intern.........................6 >> Q5a

---------------------------------------------------------------------------------------------------

Variable 8b: (All empty except for round 1)

YES .......1
NO ........2 
REFUSED...99
---------------------------------------------------------------------------------------------------

Variable 8c: (Round 1 with different coding)

YES .......1
NO ........2 
REFUSED...99
---------------------------------------------------------------------------------------------------

Variable 9: (Round 1 has different coding)

YES.1 
NO..2 >>Q11
---------------------------------------------------------------------------------------------------



SEC5A (Round 4, 5 and 6 have similar variables and coding)
---------------
Round1: 16:17,17_1,18:31 (Agriculture while the rest are non-Ag businesses) --> different coding
Round2: 11,11a:b,12:15,15a:b
Round3: 11,11a:c,12:14,15a:b
Round4: 11,11a:b,11b1,11c_1,12_1,11c,12:15
Round5: 11,11a:b,11b1,11c_1,12_1,11c,12:15
Round6: 11,11a:b,11b1,11c_1,12_1,11c,12:15
Round7: 11,11a:b,11b1,11c_1,12_1,11c,12:15,15a:b

Variable 11a:
Round2 has different coding

Open ................1 
 >> Q15 IF CASE=1,
    Q13 IF CASE=2,
    Q12 IF CASE=3,
    Q13 IF CASE=4,
    Q12 IF CASE=5
Temporarily closed ..2
Permanently closed ..3
---------------------------------------------------------------------------------------------------

Variable 12: 

Round 3: different coding
      >> Q15A IF CASE=1,
      >> Q13 IF CASE=2,
      >> Q15A IF CASE=3,
      >> Q13 IF CASE=4,
      >> Q15A IF CASE=5
      
Round2: No question transitions
---------------------------------------------------------------------------------------------------

Variable 13

Round 3: different question transitions 

Higher ......1 >> Q15A
The same ....2 >> Q15A
Less ........3
No revenue ..4

---------------------------------------------------------------------------------------------------

Variable 15:

Round 2: different variable description and coding

---------------------------------------------------------------------------------------------------

Variable 15a and 15b:
Round 2 and Round 3 have different variable descriptions.
---------------------------------------------------------------------------------------------------


SEC7 (Has all similar variables and similar coding)  
## section 7 as 8 in some rounds....

Round1: 1:8
Round2: 1:8
Round3: 1:8
Round4: 1:8
Round5: 1:8
Round6: 1:8
Round7: 1:8

SEC9(section 8 as section 9 in round 1)

Round1: 1:2
Round2: 1:9
Round3: 1:9
Round4: 1:9
Round5: 1:6,9:10 
Round6: 1:9
Round7: 3a:b,4:6,10,10b:d,11b:d,12:15

Variable 4:

Different variable descriptions.
Round 2:5 --> Has anyone in your household ever received a laboratory diagnosis for COVID-19?

Round 6:7 --> Since the last interview, has anyone in your household ever received a laboratory diagnosis for COVID-19?

--------------------------------------------------------------------------------------------------------

Variable 5:

Round 7 : Different variable description
What kind of drugs did you use for COVID-19 management?

--------------------------------------------------------------------------------------------------------

Variable 6:

Different variable description in round 7.
Which of the COVID-19 treatment method you trust the most?

--------------------------------------------------------------------------------------------------------

Variable 9:

Different variable description in round 2.
Do you think that the following measures would curb the spread of COVID19 ?

--------------------------------------------------------------------------------------------------------

Variable 10:

Different variable description in round 5 and 7.

--------------------------------------------------------------------------------------------------------

______________________________________________________________________________________
DONE CHECKING FOR CODING.
______________________________________________________________________________________