---
geometry: margin=1in
fontsize: 12pt
header-includes:
 - \usepackage{setspace}
 - \usepackage{dcolumn}
 - \usepackage[flushleft]{threeparttable}
 - \usepackage{booktabs}
 - \def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}
 - \usepackage{fontspec}
 - \setromanfont[Ligatures=TeX]{texgyrepagella-regular.otf}
 - \usepackage{unicode-math}
 - \setmathfont{texgyrepagella-math.otf}

 
figPrefix:
 - "Figure"
 - "Figures"

pairDelim: "and"

lastDelim: "and"
 
refDelim: "and"
 
output: pdf_document
---

